- README.md
I added an in my opinion great example of FRP in action: an implementation of snake using bacon.js by @philipnilsson. It's an awesome way to learn the basics of FRP while at the same time gaining appreciation for the way it can solve some problems in a really clean way.
> Added FRP tutorial to resources list.

- README.md
Highland is described as a streaming library, but it covers FRP way of doing things too.
> FRP: add Highland

- README.md
these are the one i know on the top of my head.
more (though some rather esoteric!?) might be found here:
[https://github.com/jashkenas/coffeescript/wiki/List-of-languages-that-compile-to-JS](https://github.com/jashkenas/coffeescript/wiki/List-of-languages-that-compile-to-JS)
> README: add functional languages that compile to JS

- README.md
Tiny but useful library to create tagged constructors.
> Adds daggy

- README.md
There is still work that could and should be done, most importantly to go through all resources again and ensure their awesomeness, remove duplicates, and write more precise definitions. Also, resources could be sorted by experience level.
Because the weekend's over and I won't be able to work on this next week, I suggest to merge despite the shortcomings mentioned above :smile:
> Reorganization

- README.md
refs https://github.com/sindresorhus/awesome/pull/612
> drops people section

- README.md
@stoeffel What do you think? Too short? Too abstract? I tried to find a balance between the two, for more detail there's always the articles section …
Based off of https://wiki.haskell.org/Functional_programming
> Add introduction to Functional Programming

- README.md
Hey not sure if this qualifies as awesome but here's a library built on top of the ES2015 iteration protocols for creating and manipulating lazy iterables in a Haskell/Clojure inspired manner
> Add imlazy

- README.md
Article added : 
> * [So You Want to be a Functional Programmer](https://medium.com/@cscalfani/so-you-want-to-be-a-functional-programmer-part-1-1f15e387e536) - Easy to understand, with some examples, introduction to Functional Programming in Javascript and Elm.
> Add Charles Scalfani medium articles

- README.md
https://github.com/aearly/icepick
> Add Icepick to Immutable Data Strucutres section

- README.md
Hi!
I want to add this language to the `Functional Languages that Compile to JavaScript` list.
[Quack](https://github.com/quack/quack) is a multi-paradigm programming language that is under active development, I hope you enjoy it!
> Add Quack programming language

- README.md
Added to Articles:  "Functional Programming for JavaScript People" - A complete introduction to functional programming patterns by Chet Corcos with a lot of javascript examples.
> Add Functional Programming for JavaScript People

- README.md
Added in videos a series by Mattias Petter Johansson, from the youtube channel FunFunFunction, that is specifically about popularization of functional programming in JavaScript.
> Add FunFunFunction functional programming series

- README.md
Added to Videos : "Anjana Vakil: Learning Functional Programming with JavaScript - JSUnconf 2016" - A simple and understandable introduction of functional proramming in javascript.
> Learning Functional Programming with JavaScript

- README.md
The async problem of javascript has been missing a functional solution based on promises. I created this library to make functional programming with promises easy. It has been accepted by the open souce [async-problem](https://github.com/plaid/async-problem) repo.
It's unique. There is [a functional async library using Future pattern](https://github.com/ramda/ramda-fantasy), but `bluebird-promisell` is using Promises. And is the only functional library for Promises. Another uniqueness is that, `bluebird-promisell` is built on top of bluebird in order to take advantage of bluebird's awesome performance. 
This library has [test cases with 100% code coverage](https://travis-ci.org/zhangchiqing/bluebird-promisell#L431). I've been using it on production for half a year. 
For more detail, …
> Add "bluebird-promisell" under "Libraries"

- README.md
Add "Master the JavaScript Interview: What is Functional Programming?" by @ericelliott to Articles.
> Add an article from Eric Elliott

- README.md
Added an awesome article on functional programming concepts with examples in Immutable.js.
> Added an article to Articles section

- README.md
A series of articles on learning functional programming and compositional software techniques in JavaScript ES6+ from the ground up by @ericelliott
> Add "Composing Software" to Articles

- README.md
Add Fable F# to JavaScript compiler
> Add F# to section Functional Languages that Compile to JavaScript

- README.md
https://github.com/d-plaindoux/parsec : Under development, but already useable. 100% test covered.
> Adding Javascript Parser Combinator

- README.md
Add collectable to the Data Structures section.
https://github.com/frptools/collectable
> Add collectable to Data Structures

- README.md
Hello!
I would like to suggest adding to your list a free "Functional Programming Exercises for Beginners" course. It will help to solidify the knowledge people have after books or video courses. At this moment it has about 70 exercises which covered the next concepts:
* Function, Higher-order function
* Currying
* Predicate
* Map
* Filter
* Chain
* Reduce
* Sort
* Zip
* Composition
We support this course and plan to extend it in the future.
> Add "FP for Beginners" practical course

- README.md
A complete introduction to functional programming in javascript made it easy by ES6.
https://www.youtube.com/watch?v=FYXpOjwYzcs
> Add "Functional Programming Basics In ES6" in videos

- README.md
- Add the nice pico-lambda library: https://github.com/trainyard/pico-lambda
> Add pico-lambda

- README.md
I've added ftor to the tool section.
It's a pluggable runtime type checker that supports parametric and row polymorphism, implicit rank-2 types and ADTs via Scott encoding.
Hopefully you find it helpful too.
https://github.com/kongware/ftor
> ftor - a pluggable runtime type checker and functional debugging tool

- README.md
- Add the ramda-adjunct library : https://github.com/char0n/ramda-adjunct
> Add ramda-adjunct

- README.md
according to char0n/ramda-adjunct#294
> Fix Ramda Adjunct description

- README.md
add https://github.com/funkia/list to data structures.
> add funkia/list

- README.md
fpEs: A small library provides simple usages of basic FP & pattern-matching/sumtype & MonadIO/Rx & Optional for Javascript
In fact I've implemented almost same features in Golang/Java/ES6. (Java is harder to release a library indeed...only golang & es6 versions are shared)
However I found ES6 is the most elegant version in them :P
Ref:
https://github.com/TeaEntityLab/fpEs
https://github.com/TeaEntityLab/fpGo
Thx :D
> Add TeaEntityLab/fpEs library (A small library provides simple usages of basic FP & pattern-matching/sumtype & MonadIO/Rx & Optional for Javascript  )

- README.md
Short and easy to understand article about implementing anonymous recursion in JavaScript.
https://dev.to/simov/anonymous-recursion-in-javascript
Going *arrows* all the way + recursion = anonymous recursion
> Add "Anonymous Recursion in JavaScript" in articles

- README.md
Pure is a project of mine that tries to bring FP into the JS/TS world by providing idiomatic and beginner-friendly APIs.
> Add (my own) pure library

- README.md
Recent video on the subject of ADT in JS. The AV quality is spotty in parts, but an interesting presentation. References RxJS and ramda.
> Add "Programmers Should Learn ADT's" video

- README.md
I am the author of the library.
Due to NSFW search results the library name was changed so I would like to update the name here as well.
> Rename pure to purify

- README.md
I've published a TypeScript Grid Computing Framework supporting the **RFC** (Remote Function Call). I think my library can help extending paradigm of functional programming in TS (JS) from single application to network and thread (process) level. May you accept my PR?
- https://github.com/samchon/tstl/issues/22
- https://github.com/samchon/tgrid
> Add TGrid in Libraries

- README.md
Added holdem-eval to the excercise
> Added holdem-eval to the list

- README.md
https://github.com/adobe/ferrum
> Add library: ferrum.js

- README.md
`fp-ts` provides developers with popular patterns and reliable abstractions from typed functional languages in TypeScript.
> Add fp-ts library

- README.md
While being a multi-paradigm language, TypeScript powerful type system offers many improvements to the functional programming style (eg ADT, function types).
> Add TypeScript language

- README.md
The website currently linked returns a 404.
> Fix functional.js URL

- README.md
Add more typescript, category theory info and tagging proposal.  
Also added iter-tools, remeda libs.
> Add more typescript, category theory info

- README.md
Add my new book Grokking Simplicity, which was recently published in early access at Manning.
https://www.manning.com/books/grokking-simplicity
> Add Grokking Simplicity (book)

- README.md
[`lfi`](https://github.com/TomerAberbach/lfi) is a lazy functional iteration library supporting sync, async, and concurrent iteration. The concurrent iterable concept is probably the most interesting part of the library.
> Add `lfi` package

- README.md
https://github.com/mnasyrov/ditox
> Add Ditox.js

- README.md
https://github.com/mnasyrov/rx-effects
> Add RxEffects

- README.md
https://mobily.github.io/ts-belt/docs
> Add ts-belt

- README.md
https://github.com/true-myth/true-myth
> A library for safe, idiomatic null and error handling in TypeScript, with Maybe and Result types, supporting both a functional style and a more traditional method-call style.
> Add true-myth library

- README.md
I added a library called [hyogwa](https://github.com/ENvironmentSet/hyogwa). It's an effect system implement for typescript.
> Add hyogwa library

- README.md
Link currently leads to a `404` page. I've looked around and it seems they've stopped working on this project.
> Remove paqmind resource

- README.md
Added Verticalize, a super lightweight function that looks and behaves like a pipe operator. https://github.com/laurentpayot/verticalize
> Added Verticalize

- README.md
Added PureEval, A powerful JavaScript functional programming toolset, including utility functions and abstract data structures.
https://github.com/PureEval/PureEval
> Add PureEval

- README.md
Adding fp-filters to the libraries list.
It is a curated collection of 130+ common-use filter functions. So that you will "never" have to write another filter function again.
> Add fp-filters library
